#!/bin/bash
source "$SUBITASH_ROOT"/lib/helpers/ensureFolder
source "$SUBITASH_ROOT"/lib/helpers/getTaskRoot

function createWorkspace() {
  TASK_ROOT=$(getTaskRoot)/"$1"
  ensureFolder "$TASK_ROOT"
  cp "$SUBITASH_ROOT"/lib/templates/workspace "$TASK_ROOT"/"$1".code-workspace
}
